
###
POST http://localhost:3002/api/tasks
Content-Type: application/json

{
    "title": "Задача 1",
    "date": "00.00.00"
}

###
GET http://localhost:3002/api/tasks
Content-Type: application/json

###
PUT http://localhost:3002/api/tasks
Content-Type: application/json

{
    "id": 7,
    "title": "Задача 2",
    "date": "00.00.00"
}

###
DELETE http://localhost:3002/api/tasks
Content-Type: application/json

{
    "id": 7
}